---
title: "Unit 1: Installing R"
author: "Steven Rashin"
date: "`r Sys.Date()`"
output:
    bookdown::html_document2:
      highlight: zenburn
      toc: true
      toc_float: true
      code_folding: hide
      number_sections: false
      # xaringan::moon_reader()
      # lib_dir: libs
      # mathjax: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"
      #css: xaringan::xaringan-themer.css
      #nature:
      #  highlightStyle: github
      #  highlightLines: true
      #  countIncrementalSlides: false
---

# Install R and R Studio

1)  Install R <https://cran.r-project.org/>. MAKE SURE YOU INSTALL THE CORRECT VERSION.

Note that if you don't have administrator privileges you won't be able to install R.

-   To tell the type of Mac you have, go to the apple icon in the top left of the screen and click "About This Mac"
-   For an M1/M2 Mac <https://mirrors.nics.utk.edu/cran/bin/macosx/big-sur-arm64/base/R-4.3.1-arm64.pkg>
-   For an intel based mac <https://mirrors.nics.utk.edu/cran/bin/macosx/big-sur-x86_64/base/R-4.3.1-x86_64.pkg>
-   For Windows <https://cran.r-project.org/bin/windows/base/>
      - If you run into issues, start here <https://cran.r-project.org/bin/windows/base/rw-FAQ.html#How-do-I-install-R-for-Windows_003f>
-   For Linux <https://cran.r-project.org/bin/linux/>

2) Install R Studio <https://www.rstudio.com/products/rstudio/download>.  I use the free R Studio Desktop version.  You can use other versions if you want, but, to the extent that they may be different, my ability to help you troubleshoot will be limited.  R Studio is a integrated development environment for R. "It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, debugging and workspace management (R Studio 2022)."

## Additional Mac Components

If you have a mac you likely need to install XQuartz <https://www.xquartz.org/>, Xcode <https://apps.apple.com/us/app/xcode/id497799835?mt=12>, and install command line developer tools from within Xcode. When you open Xcode for the first time there will be an option to do this. If not, in the terminal type:

xcode-select --install

If you don't know how to get to the terminal, you can search for it in Applications, Finder, or hit shift + command + u and then find the terminal application.

# Links 

The next section is in bold.

[0 - Project Home](https://sdr1.github.io/R-Intro-Seminar)

[1 - Installing R and R Studio](https://sdr1.github.io/R-Intro-Seminar/1-r-intro-seminar.html)

[**2 - Coding Principles and Debugging** ](https://sdr1.github.io/R-Intro-Seminar/2-intro-to-coding-debugging.html)

[3 - R Studio Intro](https://sdr1.github.io/R-Intro-Seminar/3-intro-to-r-studio.html)

[4 - Basic Coding](https://sdr1.github.io/R-Intro-Seminar/4-basic-coding.html)


# Appendix 1: Integrating with Other Programming Languages

You may wish to use other languages in addition to R. R and R Studio can do this, although sometimes the process of integrating another programming language takes too long and you're better of just using the languages separately.

## Python 
Rstudio and Python now can coexist peacefully.  This state of affairs may (or may not) last.  If you want to create documents that integrate both R and Python, follow the following steps:

1. Download Anaconda
2. In the Anaconda launcher, setup a new conda environment. I call mine "anaconda3"
3. Install packages you care about there, such as tensorflow and keras (for machine learning)
4. When you're in R, run the following commands

```{r, eval = F, echo = T}
install.packages('reticulate')
library(reticulate)
use_condaenv("/Users/stevenrashin/anaconda3/envs/anaconda3/bin/python")
```

## Java (with M1 Macs)

First, see if you can do whatever you want to do without using Java.

Second, if it's inevitable 1) I'm sorry and 2) what works currently may not work in a few months. The current solution to the problem is here in section 6.3.2. <https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#macOS-packages>

## Fortran or C++

See <https://mac.r-project.org/tools/>

## Latex

See <https://bookdown.org/yihui/rmarkdown-cookbook/install-latex.html>.

For the full latex version, go here <https://www.latex-project.org/get/>.